version: '3'
services:
        limo_foxy:
                network_mode: host
                volumes:
                        - '/dev:/dev'
                        - '/tmp/.X11-unix:/tmp/.X11-unix'
                privileged: true
                environment:
                        - "XAUTHORITY=$AUTH"
                        - "LIBGL_ALWAYS_SOFTWARE=1"
                        - "DISPLAY=$DISPLAY"
                        - "AUTH=$AUTH"
                device_cgroup_rules:
                        - "a *:* rmw"
                tty: true
                runtime: nvidia
                restart: always
                build: ./limo-foxy
                image: limo-foxy
                container_name: limo_foxy_dev

